Repository ceoslidi/firework, pull requests merged in 2022-02, with the labels that each got.

#17 Feat: support of @foreach loop and @if in views
  firework/View.php
Labels: enhancement

#19 Fix: Gulp for Unix
  gulpfile.js
Labels: bug

#22 Docs: added documentation for classes
  README.md
  composer.json
  config/Config.php
  firework/Controller.php
  firework/Database.php
  firework/Env.php
  firework/File.php
  firework/Hash.php
  firework/Installer.php
  firework/Request.php
  firework/Response.php
  firework/Router.php
  firework/Run.php
  firework/Session.php
  firework/View.php
Labels: documentation
